# Site settings
title: CLE Protests Jail Support
email: clevelandaction@gmail.com
url: cleprotestsjailsupport.com
description: "Jail Support for Cleveland Protesters, from the Brelo Verdict 71 and on until the City of Cleveland can recognize that #BlackLivesMatter"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://facebook.com/clevelandaction

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
