# Site settings
title: CLE Movement Law
email: clevelandaction@gmail.com
url: http://cleprotestsjailsupport.com
baseurl: ''
description: "Jail & Legal Support & Resources for Cleveland Protesters, activists & freedom fighters who are working towards a city where All Black Lives Matter"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
cleactsocial:
  - title: envelope
    url: mailto:clevelandaction@gmail.com
  - title: facebook
    url: https://facebook.com/clevelandaction

nlgsocial:
  - title: envelope
    url: mailto:cleveland@nlg.org
  - title: facebook
    url: https://www.facebook.com/ohionlg/
  - title: phone
    url: tel:216-505-0654

# Postal address (add as many lines as necessary)
nlgphone: 216-505-0654

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
